version: '2.23'

services:
  db:
    image: postgres:16.2-alpine
    volumes:
      - ./pg_dump.sql:/docker-entrypoint-initdb.d/pg_dump.sql
      - /var/lib/postgres/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5430:5432'

  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - '3000:3000'

